djangocommerce/accounts/urls.py
from django.contrib.auth.views import login, logout
from django.urls import path
from accounts.views import signup

app_name='accounts'

urlpatterns = [
    path("login", login, {'template_name': 'accounts/login.html'}, name="login"),
    path("logout", logout, {'next_page':'/'}, name="logout"),
    path("signup", signup, name="signup"),
]

djangocommerce/comments/urls.py
from comments.views import create_comment
from django.urls import path

app_name='comments'

urlpatterns = [
    path('createcomment', create_comment, name="createcomment")
]

djangocommerce/djangocommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('test/', TemplateView.as_view(template_name='products/test.html')),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('comments/', include('comments.urls', namespace="comments")),
    path('', include('products.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)

djangocommerce/products/urls.py
from django.urls import path
from products. views import HomeView, ProductDetailView, ProductBuyView

urlpatterns  = [
    path("", HomeView.as_view(), name="home"),
    path("products/<slug:slug>", ProductDetailView.as_view(), name="detail"),
    path("products/<slug:slug>/buy", ProductBuyView.as_view(), name="buy"),
]

djangocommerce/accounts/models.py
from django.db import models

# Create your models here.

djangocommerce/comments/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Comment(models.Model):
    content = models.TextField()
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete = models.CASCADE,
        related_name='comments'
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    product = models.ForeignKey(
        'products.Product',
        related_name='comments',
        on_delete=models.CASCADE
    )


    def __str__(self):
        return self.content[:20]

djangocommerce/products/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

# Create your models here.
class Product(models.Model):
    title = models.CharField(max_length=255)
    descripcion = models.CharField(max_length=255)
    price = models.IntegerField()
    slug = models.SlugField()
    categories = models.ManyToManyField('products.ProduCategory')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("detail", kwargs={'slug': self.slug})

    def __str__(self):
        return self.title

class ProductImage(models.Model):
    product = models.ForeignKey(
        'products.Product', on_delete=models.CASCADE,
        related_name='images'
    )
    image = models.ImageField()

    def __str__(self):
        return self.image.url

class ProduCategory(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class LogBuy(models.Model):
    product = models.ForeignKey(
        'products.Product',
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "product {} buyed".format(self.product)

djangocommerce/comments/forms.py
from django import forms
from comments.models import Comment

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['content', 'product']

djangocommerce/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def signup(request):
    form = UserCreationForm(request.POST or None)

    if form.is_valid():
        form.save()
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('home')
    return render(request, "accounts/signup.html", {'form': form})

djangocommerce/comments/views.py
from django.shortcuts import render, redirect
from comments.forms import CommentForm
from django.http import HttpResponseBadRequest

# Create your views here.
def create_comment(request):
    form = CommentForm(request.POST)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.save()
        return redirect(comment.product.get_absolute_url())
    return HttpResponseBadRequest()

djangocommerce/products/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, DetailView
from products.models import Product, LogBuy
from comments.forms import CommentForm
import stripe
from django.conf import settings
# Create your views here.
class HomeView(TemplateView):
    template_name = 'products/home.html'

    def get_context_data(self, *args, **kwargs):
        products = Product.objects.all()
        return {'products':products}

class ProductDetailView(DetailView):
    model = Product

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        comment_form = CommentForm()
        context['comment_form'] = comment_form
        return {'comment_form': comment_form}

class ProductBuyView(DetailView):
    model = Product
    template_name = 'products/buy.html'

    def post(self, requst, *args, **kwargs):
        stripe.api_key = settings.STRIPE_API_KEY
        token = request.POST['stripeToken']
        product = self.get_object()
        error_message = None

        try:
            charge = stripe.Chage.create(
                amount=product.price,
                currency='usd',
                description="cobro por {}".format(product.title),
                statement_descriptor="cobro djangocommerce",
                source=token
            )
        except stripe.error.CardError as e:
            body = e.json_body
            err = body['error']
            error_message = error['message']
        except stripe.error.StripeError as e:
            error_message = "can't process your paiment"

        if error_message:
            return render(request, "products/failed.html", {'error_message': error_message, 'product':product})


        buyer = None
        if request.user.is_autenticated:
            buyer = request.user

        LogBuy.objects.create(product=product, user=buyer)

        return render(request, "products/success.html", {'debug_info':charge, 'product':product})

djangocommerce/accounts/templates/accounts/login.html
{% extends 'products/base.html' %}
{% load staticfiles %}
{% block css %}
  <link href="{% static "css/3-col-portfolio.css" %}" rel="stylesheet">
{% endblock css%}
{% block title %}Login{% endblock %}

{% block content %}
<div class="container">
  <div class="row align-items-center">
    <div class="col"></div>
    <div class="col">
      <br>
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><button type="submit">Login</button></p>
  </form>

</div>
<div class="col"></div>
</div>
</div>
{% endblock %}

djangocommerce/accounts/templates/accounts/signup.html
{% extends 'products/base.html' %}
{% load staticfiles %}
{% block css %}
  <link href="{% static "css/3-col-portfolio.css" %}" rel="stylesheet">
{% endblock css%}
{% block title %}Login{% endblock %}

{% block content %}
<div class="content">

<div class="row">
  <div class="col-md-3">
  </div>
  <div class="col-md-9">
    <h2>Sign up</h2>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Sign up</button>
    </form>

  </div>

</div>

</div>
{% endblock %}

djangocommerce/products/templates/products/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{title|default:"djangocommerce"}}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://bootswatch.com/4/minty/bootstrap.min.css" rel="stylesheet">
    <!-- <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet"> -->

    <!-- Custom styles for this template -->

    {% block css %}{% endblock css %}
  </head>

  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">DjangoCommerce</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#"></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#"></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#"></a>
            </li>
            {% if request.user.is_authenticated%}
            <li class="nav-item">
              {{request.user.username}}/<a class="nav-link" href="{% url "accounts:logout" %}">logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url "accounts:login" %}">Login</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    {% block content %}
    {% endblock content %}
    <!-- Footer -->
    <footer class="py-2 bg-primary">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; platzi {% now "Y" %}</p>
      </div>
      <!-- /.container -->
    </footer>
  {% block js%}{% endblock %}
    <!-- Bootstrap core JavaScript -->
    <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
    <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

  </body>

</html>

djangocommerce/products/templates/products/buy.html
{% extends "products/base.html" %}
{% load staticfiles %}
{% block css %}
<link href="{% static "css/3-col-portfolio.css" %}" rel="stylesheet">

<style type="text/css">
#product-image {
  max-width: 350px;
}
</style>

{% endblock %}
{% block content %}
<script src="https://js.stripe.com/v3/"></script>
<div class="container">

  <div class="row p-3">
		<div class="col-xs-2 m-3 card"><img id="product-image" class="img-responsive" src="{{product.images.first.image.url}}">
		</div>
		<div class="col-xs-4 m-3">
			<h4 class="product-name"><strong>{{object.title}}</strong></h4><h4><small>{{object.description}}</small></h4>
		</div>
	</div>
<div class="row p-2 ">
  <div class="col-xs-12 col-md-6">
  <form action="." method="post" id="payment-form">
    {% csrf_token %}

    <h2>Payment Data</h2>
    <br>
    <div id="card-element">
      <!-- a Stripe Element will be inserted here. -->
    </div>
    <div id="card-errors" role="alert"></div>
    <br>
    <button type="submit" class="btn btn-success">Buy</button>
  </form>

  </div>
  </div>
</div>


<script type="text/javascript">
var stripe = Stripe('<your publish key >');
var elements = stripe.elements();



var style = {
  base: {
    color: '#32325d',
    lineHeight: '18px',
    fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
    fontSmoothing: 'antialiased',
    fontSize: '20px',
    '::placeholder': {
      color: '#aab7c4'
    }
  },
  invalid: {
    color: '#fa755a',
    iconColor: '#fa755a'
  }
};
// Create an instance of the card Element
var card = elements.create('card', {style: style});

// Add an instance of the card Element into the `card-element` <div>
card.mount('#card-element');

card.addEventListener('change', function(event) {
  var displayError = document.getElementById('card-errors');
  if (event.error) {
    displayError.textContent = event.error.message;
  } else {
    displayError.textContent = '';
  }
});


function stripeTokenHandler(token) {
  console.log(token);
  // // Insert the token ID into the form so it gets submitted to the server
  var form = document.getElementById('payment-form');
  var hiddenInput = document.createElement('input');
  hiddenInput.setAttribute('type', 'hidden');
  hiddenInput.setAttribute('name', 'stripeToken');
  hiddenInput.setAttribute('value', token.id);
  form.appendChild(hiddenInput);

  // Submit the form
  form.submit();
}
// Create a token or display an error when the form is submitted.
var form = document.getElementById('payment-form');
form.addEventListener('submit', function(event) {
  event.preventDefault();

  stripe.createToken(card).then(function(result) {
    if (result.error) {
      // Inform the customer that there was an error
      var errorElement = document.getElementById('card-errors');
      errorElement.textContent = result.error.message;
    } else {
      // Send the token to your server
      // console.log(result.token);
      stripeTokenHandler(result.token);
    }
  });
});
</script>
{% endblock content %}

djangocommerce/products/templates/products/failed.html
{% extends "products/base.html" %}
{% load staticfiles %}
{% block css %}
  <link href="{% static "css/3-col-portfolio.css" %}" rel="stylesheet">
{% endblock%}

{% block content %}
<div class="container">

<div class="row">
  <div class="col-xs-12 col-md-12 m-3">
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading">Payment failed</h4>
      <p>Sorry, something happened with the payment to {{product.title}}</p>
      <p>{{error_message}}</p>
      <hr>
    </div>
    <a href="/"><button type="button" class="btn btn-primary", name="button">Volver</button></a>
  </div>

</div>
</div>
{% endblock %}

djangocommerce/products/templates/products/home.html
{% extends "products/base.html" %}
{% load staticfiles %}
{% block css %}
  <link href="{% static "css/3-col-portfolio.css" %}" rel="stylesheet">
{% endblock css%}

{% block content %}
    <!-- Page Content -->
    <div class="container">

      <!-- Page Heading -->
      <h1 class="my-4">Products
        <!-- <small>buy one</small> -->
      </h1>

      {% for product in products %}
      {% if forloop.counter0 != 0 and forloop.counter0|divisibleby:"3" %}
      </div>
      {% endif %}
      {% if forloop.counter0|divisibleby:"3" %}
      <div class="row">
      {% endif %}
      <div class="col-lg-4 col-sm-6 portfolio-item">
        <div class="card h-100">
          <a href="{{product.get_absolute_url}}"><img class="card-img-top" src="{{product.images.first.image.url}}" alt=""></a>
          <div class="card-body">
            <h4 class="card-title">
              <a href="{{product.get_absolute_url}}">{{product.title}}</a>
            </h4>
            <p class="card-text">{{product.descripcion}}</p>
          </div>
        </div>
      </div>
      {% endfor %}
      </div>
<!--
      <div class="row">
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project One</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur eum quasi sapiente nesciunt? Voluptatibus sit, repellat sequi itaque deserunt, dolores in, nesciunt, illum tempora ex quae? Nihil, dolorem!</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Two</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Three</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos quisquam, error quod sed cumque, odio distinctio velit nostrum temporibus necessitatibus et facere atque iure perspiciatis mollitia recusandae vero vel quam!</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Four</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Five</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Six</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque earum nostrum suscipit ducimus nihil provident, perferendis rem illo, voluptate atque, sit eius in voluptates, nemo repellat fugiat excepturi! Nemo, esse.</p>
            </div>
          </div>
        </div>
      </div> -->
      <!-- /.row -->

      <!-- Pagination -->
      <!-- <ul class="pagination justify-content-center">
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">1</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">2</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">3</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
      </ul> -->

    </div>
    <!-- /.container -->
{% endblock content%}

djangocommerce/products/templates/products/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block css %}
  <link href="{% static "css/3-col-portfolio.css" %}" rel="stylesheet">
  <style media="screen">
    a {
      color: white;
    }
  </style>
{% endblock css%}

{% block content %}
    <!-- Page Content -->
    <div class="container">

      <!-- Page Heading -->
      <h1 class="my-4">Products
        <!-- <small>buy one</small> -->
      </h1>

      {% for product in products %}
      {% if forloop.counter0 != 0 and forloop.counter0|divisibleby:"3" %}
      </div>
      {% endif %}
      {% if forloop.counter0|divisibleby:"3" %}
      <div class="row">
      {% endif %}
      <div class="col-lg-4 col-sm-6 portfolio-item">
        <div class="card h-100">
          <a href="{{product.get_absolute_url}}"><img class="card-img-top" src="{{product.images.first.image.url}}" alt=""></a>
          <div class="card-body">
            <h4 class="card-title">
              <a href="{{product.get_absolute_url}}">{{product.title}}</a>
            </h4>
            <p class="card-text">{{product.description}}</p>
          </div>
        </div>
      </div>
      {% endfor %}
      </div>
<!--
      <div class="row">
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project One</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur eum quasi sapiente nesciunt? Voluptatibus sit, repellat sequi itaque deserunt, dolores in, nesciunt, illum tempora ex quae? Nihil, dolorem!</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Two</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Three</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos quisquam, error quod sed cumque, odio distinctio velit nostrum temporibus necessitatibus et facere atque iure perspiciatis mollitia recusandae vero vel quam!</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Four</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Five</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Six</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque earum nostrum suscipit ducimus nihil provident, perferendis rem illo, voluptate atque, sit eius in voluptates, nemo repellat fugiat excepturi! Nemo, esse.</p>
            </div>
          </div>
        </div>
      </div> -->
      <!-- /.row -->

      <!-- Pagination -->
      <!-- <ul class="pagination justify-content-center">
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">1</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">2</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">3</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
      </ul> -->

    </div>
    <!-- /.container -->
{% endblock content%}

djangocommerce/products/templates/products/product_detail.html
{% extends 'products/base.html' %}
{% load staticfiles %}
{% block css %}
  <link href="{% static "css/3-col-portfolio.css" %}" rel="stylesheet">
{% endblock css%}
{% block content %}

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Title -->
          <h1 class="mt-4">{{product.title}}</h1>

          <!-- Author -->
          <!-- <p class="lead">
            by
            <a href="#">Start Bootstrap</a>
          </p> -->

          <hr>

          <!-- Date/Time -->
          <p>Posted on {{product.created_at}}</p>

          <hr>

          <!-- Preview Image -->
          <img class="img-fluid rounded" src="{{product.images.first.image.url}}" alt="">

          <hr>

          <!-- Post Content -->
          <p class="lead">{{product.descripcion}}</p>

          <hr>

          <!-- Comments Form -->
          {% if request.user.is_authenticated %}
          <h4 id="comments">Comments</h4>
          <div class="card my-4">
            <h5 class="card-header">Leave a Comment:</h5>
            <div class="card-body">
              <form method="post" action="{% url "comments:createcomment" %}">
                {% csrf_token %}
                <div class="form-group">
                  <textarea name="{{comment_form.content.name}}" class="form-control" rows="3"></textarea>
                  <input type="hidden" name="{{comment_form.product.name}}" value="{{product.id}}">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
              </form>
            </div>
          </div>
          {% endif %}

          <!-- Single Comment -->
          <div id="0" class="media mb-4">
            {% for comment in product.comments.all %}
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">{{comment.author.username}}</h5>
              {{comment.content}}
            </div>
            {% endfor %}
          </div>

        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Search Widget -->
          <div class="card my-4">
            <h5 class="card-header">Search</h5>
            <div class="card-body">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                  <button class="btn btn-secondary" type="button">Go!</button>
                </span>
              </div>
            </div>
          </div>

          <!-- Categories Widget -->
          <div class="card my-4">
            <h5 class="card-header">Categories</h5>
            <div class="card-body">
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    {% for category in product.categories.all %}
                    <li>
                      <a href="#">{{category.name}}</a>
                    </li>
                    {% endfor %}
                  </ul>
                </div>

            </div>
          </div>

          <div class="card my-4">
            <h5 class="card-header">Pricing</h5>
            <div class="card-body">
              Only ${{product.price}}
              <a href="{% url "buy" slug=product.slug %}"><button type="button" class="btn btn-success">Buy</button></a>
            </div>
          </div>

        </div>

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

{% endblock content %}

djangocommerce/products/templates/products/success.html
{% extends "products/base.html" %}
{% load staticfiles %}
{% block css %}
  <link href="{% static "css/3-col-portfolio.css" %}" rel="stylesheet">
{% endblock%}

{% block content %}
<div class="container">

<div class="row">
  <div class="col-xs-12 col-md-12 m-3">
    <div class="alert alert-info" role="alert">
      <h4 class="alert-heading">Payment success</h4>
      <p>Congratuliations, you just buy {{product.title}}</p>
      <hr>
      <p>DEBUG INFO {{debug_info}}</p>
    </div>
    <a href="/"><button type="button" class="btn btn-primary", name="button">Volver</button></a>
  </div>

</div>
</div>
{% endblock %}

djangocommerce/products/templates/products/test.html
{% extends "products/base.html" %}
{% load staticfiles %}
{% block css%}
<link href="{% static "css/3-col-portfolio.css" %}" rel="stylesheet">
<style media="screen">
  a {
    color: white;
  }
</style>
{% endblock %}
{% block content %}
<h1>Hello</h1>
{% endblock %}